markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]
title : sahan.me
production_url : http://sahan.github.io
description: "Random Musings From An OSS Enthusiast."
disqus_shortname: lahirusj
analytics: UA-40937518-1
author :
  name : Lahiru Sahan Jayasinghe
  github : sahan
  twitter : lahirusj
  coderwall : sahan
  email: lahiru@lonepulse.com
